import type { Metadata } from "next";
import {Poppins as FontSans} from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import React from "react";

const fontSans = FontSans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight:  ["300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('min-h-screen bg-background font-sans antialiased ',  fontSans.variable)}
      >
        <div className="flex h-screen flex-col">
        <Header />
      <main className="wrapper flex-1">  {children}</main>
        <Footer/>
        </div>
      </body>
    </html>
  );
}
